# Generated by Django 4.1 on 2022-08-29 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EcomApp', '0003_product_color_product_search_key'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='search_key',
            field=models.TextField(),
        ),
    ]
