# Generated by Django 4.1 on 2022-08-30 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EcomApp', '0004_alter_product_search_key'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='for_gender',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female')], default=2, max_length=128),
            preserve_default=False,
        ),
    ]
