# Generated by Django 4.1 on 2022-08-30 20:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('EcomApp', '0006_post_reviews'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post_reviews',
            old_name='reviews',
            new_name='review',
        ),
    ]
