# Generated by Django 4.1 on 2022-09-08 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EcomApp', '0008_cart_cartitems'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='get_id',
            field=models.IntegerField(default=2),
            preserve_default=False,
        ),
    ]
