# Generated by Django 4.1 on 2022-09-08 08:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('EcomApp', '0009_cart_get_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='get_id',
        ),
    ]
