# Generated by Django 4.1 on 2022-08-31 12:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('HomeApp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='useraddress',
            old_name='country',
            new_name='state',
        ),
    ]
