# Generated by Django 4.0.4 on 2022-09-03 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HomeApp', '0003_alter_useraddress_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='useraddress',
            name='phone',
            field=models.IntegerField(default=0),
        ),
    ]
