# Generated by Django 4.1 on 2022-09-03 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HomeApp', '0005_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='amount',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='order',
            name='payment_method',
            field=models.CharField(default=2, max_length=100),
            preserve_default=False,
        ),
    ]
