# Generated by Django 4.1 on 2022-09-05 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HomeApp', '0006_order_amount_order_payment_method'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='payment_Status',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
    ]
