# Generated by Django 4.1 on 2022-09-05 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HomeApp', '0007_order_payment_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='payment_Status',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
